In [1]:
import os
import json
import pandas as pd
import mysql.connector

In [3]:
#1
path1 = "D:/SK/DS/New folder/phonepe/pulse/data/aggregated/transaction/country/india/state/"
aggregated_transaction = os.listdir(path1)

Columns1 = {"State" :[],"Year" :[],"Quarter":[],"Transaction_type":[],"Transaction_Count":[],"Transaction_Amount":[]}

for states in aggregated_transaction:
    state1 =path1 + states +"/"
    agg_year_list = os.listdir(state1)


    for year in agg_year_list:
        year1 =state1+year+"/"
        agg_file_list = os.listdir(year1)

        for file in agg_file_list:
            file1 = year1+file
            data = open (file1,"r")
            A = json.load(data)

            for i in A["data"]["transactionData"]:
                name = i["name"]
                count =i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                Columns1["Transaction_type"].append(name)
                Columns1["Transaction_Count"].append(count)
                Columns1["Transaction_Amount"].append(amount)
                Columns1["State"].append(states)
                Columns1["Year"].append(year)
                Columns1["Quarter"].append(int(file.strip('.json')))

aggregated_transaction_df = pd.DataFrame(Columns1)

aggregated_transaction_df["State"] = aggregated_transaction_df["State"].str.replace('andaman-&-nicobar-islands','Andaman & nicobar islands')
aggregated_transaction_df["State"] = aggregated_transaction_df["State"].str.replace('-',' ')
aggregated_transaction_df["State"] = aggregated_transaction_df["State"].str.replace('dadra & nagar haveli & daman & diu','dadra and nagar haveli and daman and diu')
aggregated_transaction_df["State"] = aggregated_transaction_df["State"].str.title()

In [15]:
#2
path2 ="D:/SK/DS/New folder/phonepe/pulse/data/aggregated/user/country/india/state/"
agg_user = os.listdir(path2)

Columns2 = {"State" :[],"Year" :[],"Quarter":[],"Brands":[],"Count":[],"Percentage":[]}

for states in agg_user:
    state1 = path2+states+"/"
    agg_year_list =os.listdir(state1)
   
    
    for year in agg_year_list:
        year1 =state1 +year+"/"
        agg_file_list = os.listdir(year1) 
        
        for file in agg_file_list:
            file1 = year1+file
            data = open(file1,"r")
            
            B=json.load(data)

            try:

                for i in B["data"]["usersByDevice"]:
                    brand = i["brand"]
                    count =i["count"]
                    percentage = i["percentage"]
                    Columns2["Brands"].append(brand)
                    Columns2["Count"].append(count)
                    Columns2["Percentage"].append(percentage)
                    Columns2["State"].append(states)
                    Columns2["Year"].append(year)
                    Columns2["Quarter"].append(int(file.strip('.json')))
            except:
                pass

agg_user_df = pd.DataFrame(Columns2)

agg_user_df ["State"] = agg_user_df ["State"].str.replace('andaman-&-nicobar-islands','Andaman & nicobar islands')
agg_user_df ["State"] = agg_user_df ["State"].str.replace('-',' ')
agg_user_df ["State"] = agg_user_df ["State"].str.replace('dadra & nagar haveli & daman & diu','dadra and nagar haveli and daman and diu')
agg_user_df["State"] = agg_user_df ["State"].str.title()

In [5]:
#3
path3="D:/SK/DS/New folder/phonepe/pulse/data/map/transaction/hover/country/india/state/"
map_transaction = os.listdir(path3)

Columns3 = {"State" :[],"Year" :[],"Quarter":[],"District":[],"Transaction_Count":[],"Transaction_Amount":[]}

for states in map_transaction:
    state1 = path3+states+"/"
    tran_year = os.listdir(state1)
    
    for year in tran_year:
        year1 = state1+year+"/"
        user_file = os.listdir(year1)
        
        for file in user_file:
            file1 = year1+file
            data =open (file1,"r")
            C=json.load(data)

            for i in C["data"]["hoverDataList"]:
                    District = i["name"]
                    Transaction_Count = i["metric"][0]["count"]
                    Transaction_Amount=i["metric"][0]["amount"]
                    Columns3["State"].append(states)
                    Columns3["Year"].append(year)
                    Columns3["Quarter"].append(file.strip(".json"))
                    Columns3["District"].append(District)
                    Columns3["Transaction_Count"].append(Transaction_Count)
                    Columns3["Transaction_Amount"].append(Transaction_Amount)

map_transaction_df = pd.DataFrame(Columns3)

map_transaction_df["State"] = map_transaction_df["State"].str.replace('andaman-&-nicobar-islands','Andaman & nicobar islands')
map_transaction_df["State"] = map_transaction_df["State"].str.replace('-',' ')
map_transaction_df["State"] = map_transaction_df["State"].str.replace('dadra & nagar haveli & daman & diu','dadra and nagar haveli and daman and diu')
map_transaction_df["State"] = map_transaction_df["State"].str.title()
map_transaction_df["District"] = map_transaction_df["District"].str.title()

In [6]:
#4
path4="D:/SK/DS/New folder/phonepe/pulse/data/map/user/hover/country/india/state/"
map_user = os.listdir(path4)

Columns4 = {"State" :[],"Year" :[],"Quarter":[],"District":[],"Registered_Users":[],"App_Opens":[]}

for state in map_user:
    state1 = path4+state+"/"
    user_year = os.listdir(state1)

    for year in user_year:
        year1 = state1+year+"/"
        user_file = os.listdir(year1)
    
        for file in user_file:
            file1 = year1+file
            data = open(file1,"r")
            D = json.load(data)

            for i in D["data"]["hoverData"].items():
                    district = i[0]
                    registeredUsers = i[1]["registeredUsers"]
                    appOpens =i[1]["appOpens"]
                    Columns4["State"].append(state)
                    Columns4["Year"].append(year)
                    Columns4["Quarter"].append(file.strip(".json"))
                    Columns4["District"].append(district)
                    Columns4["Registered_Users"].append(registeredUsers)
                    Columns4["App_Opens"].append(appOpens)


map_user_df = pd.DataFrame(Columns4)
map_user_df["State"] = map_user_df["State"].str.replace('andaman-&-nicobar-islands','Andaman & nicobar islands')
map_user_df["State"] = map_user_df["State"].str.replace('-',' ')
map_user_df["State"] = map_user_df["State"].str.replace('dadra & nagar haveli & daman & diu','dadra and nagar haveli and daman and diu')
map_user_df["State"] = map_user_df["State"].str.title()
map_user_df["District"] = map_user_df["District"].str.title()

In [7]:
#5
path5 = "D:/SK/DS/New folder/phonepe/pulse/data/top/transaction/country/india/state/"
top_transaction = os.listdir(path5)

Columns5 = {"State" :[],"Year" :[],"Quarter":[],"Postalcode":[],"Transaction_Count":[],"Transaction_Amount":[]}

for state in top_transaction:
    state1 = path5+state+"/"
    top_year = os.listdir(state1)
    
    for year in top_year:
        year1 = state1+year+"/"
        top_file = os.listdir(year1)
        
        for file in top_file:
            file1 = year1+file
            data=open(file1,"r")
            E = json.load(data)

            for j in E["data"]["pincodes"]:
                Postalcode=j["entityName"]
                Postal_Transaction_Count =j["metric"]["count"]
                Postal_Transaction_Amount = j["metric"]["amount"]
                Columns5["State"].append(state)
                Columns5["Year"].append(year)
                Columns5["Quarter"].append(file.strip(".json"))
                Columns5["Postalcode"].append(Postalcode)
                Columns5["Transaction_Count"].append(Postal_Transaction_Count)
                Columns5["Transaction_Amount"].append(Postal_Transaction_Amount)

top_transaction_df=pd.DataFrame(Columns5)

top_transaction_df["State"] = top_transaction_df["State"].str.replace('andaman-&-nicobar-islands','Andaman & nicobar islands')
top_transaction_df["State"] = top_transaction_df["State"].str.replace('-',' ')
top_transaction_df["State"] = top_transaction_df["State"].str.replace('dadra & nagar haveli & daman & diu','dadra and nagar haveli and daman and diu')
top_transaction_df["State"] = top_transaction_df["State"].str.title()

In [9]:
#6
path6 = "D:/SK/DS/New folder/phonepe/pulse/data/top/user/country/india/state/"
top_user = os.listdir(path6)

Columns6 = {"State" :[],"Year" :[],"Quarter":[],"Postalcode":[],"registerusers":[]}


for state in top_user:
    state1 = path6+state+"/"
    top_year = os.listdir(state1)
    
    for year in top_year:
        year1 = state1+year+"/"
        top_file = os.listdir(year1)
        
        for file in top_file:
            file1 = year1+file
            data=open(file1,"r")
            F = json.load(data)            

            for j in F["data"]["pincodes"]:
                Postalcode=j["name"]
                registerusers=j["registeredUsers"]
                Columns6["State"].append(state)
                Columns6["Year"].append(year)
                Columns6["Quarter"].append(file.strip(".json"))
                Columns6["Postalcode"].append(Postalcode)
                Columns6["registerusers"].append(registerusers)

top_user_df = pd.DataFrame(Columns6)

top_user_df["State"] = top_user_df["State"].str.replace('andaman-&-nicobar-islands','Andaman & nicobar islands')
top_user_df["State"] = top_user_df["State"].str.replace('-',' ')
top_user_df["State"] = top_user_df["State"].str.replace('dadra & nagar haveli & daman & diu','dadra and nagar haveli and daman and diu')
top_user_df["State"] = top_user_df["State"].str.title()

In [10]:
mydb = mysql.connector.connect(host="localhost",user="root",password="sk23",database='p1')
mycursor = mydb.cursor(buffered=True)

In [11]:
#1
create_query_1 ='''CREATE TABLE IF NOT EXISTS aggregated_transaction(State VARCHAR(250),Year INT,Quarter INT,
                                                Transaction_type VARCHAR(250),Transaction_Count BIGINT,Transaction_Amount BIGINT)'''
mycursor.execute(create_query_1)
mydb.commit()

insert_query_1 = '''INSERT INTO aggregated_transaction(State,Year,Quarter,Transaction_type,Transaction_Count,Transaction_Amount)
                    values(%s,%s,%s,%s,%s,%s)'''
data1 = aggregated_transaction_df.values.tolist()
mycursor.executemany(insert_query_1,data1)
mydb.commit()

#2
create_query_2 ='''CREATE TABLE IF NOT EXISTS aggregated_user(State VARCHAR(250),Year INT,Quarter INT,Brands VARCHAR(250),
                                                    Count BIGINT,Percentage FLOAT)'''
mycursor.execute(create_query_2)
mydb.commit()

insert_query_2 = '''INSERT INTO aggregated_user(State,Year,Quarter,Brands,Count,Percentage)
                    values(%s,%s,%s,%s,%s,%s)'''
data2 = agg_user_df.values.tolist()
mycursor.executemany(insert_query_2,data2)
mydb.commit()

In [12]:
#3
create_query_3 ='''CREATE TABLE IF NOT EXISTS map_transaction(State VARCHAR(250),Year INT,Quarter INT,District VARCHAR(250),
                                                    Transaction_Count BIGINT,Transaction_Amount BIGINT)'''
mycursor.execute(create_query_3)
mydb.commit()

insert_query_3 = '''INSERT INTO map_transaction(State,Year,Quarter,District,Transaction_Count,Transaction_Amount)
                    values(%s,%s,%s,%s,%s,%s)'''
data3 = map_transaction_df.values.tolist()
mycursor.executemany(insert_query_3,data3)
mydb.commit()

#4
create_query_4 ='''CREATE TABLE IF NOT EXISTS map_user(State VARCHAR(250),Year INT,Quarter INT,District VARCHAR(250),
                                                   Registered_Users BIGINT,App_Opens BIGINT)'''
mycursor.execute(create_query_4)
mydb.commit()

insert_query_4 = '''INSERT INTO map_user(State,Year,Quarter,District,Registered_Users,App_Opens)
                    values(%s,%s,%s,%s,%s,%s)'''
data4 = map_user_df.values.tolist()
mycursor.executemany(insert_query_4,data4)
mydb.commit()

In [13]:
#5
create_query_5 ='''CREATE TABLE IF NOT EXISTS top_transaction(State VARCHAR(250),Year INT,Quarter INT,Postalcode INT,
                                                   Transaction_Count BIGINT,Transaction_Amount BIGINT)'''
mycursor.execute(create_query_5)
mydb.commit()

insert_query_5 = '''INSERT INTO top_transaction(State,Year,Quarter,Postalcode,Transaction_Count,Transaction_Amount)
                    values(%s,%s,%s,%s,%s,%s)'''
data5 = top_transaction_df.values.tolist()
mycursor.executemany(insert_query_5,data5)
mydb.commit()

#6
create_query_6 ='''CREATE TABLE IF NOT EXISTS top_user(State VARCHAR(250),Year INT,Quarter INT,Postalcode INT,
                                                   Registered_Users BIGINT)'''
mycursor.execute(create_query_6)
mydb.commit()

insert_query_6 = '''INSERT INTO top_user(State,Year,Quarter,Postalcode,Registered_Users)
                    values(%s,%s,%s,%s,%s)'''
data6 = top_user_df.values.tolist()
mycursor.executemany(insert_query_6,data6)
mydb.commit()